// <auto-generated />
using System;
using DojoActivityCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DojoActivityCenter.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200224154706_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DojoActivityCenter.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("coordinator");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<string>("desc");

                    b.Property<int>("duration");

                    b.Property<string>("durationlength");

                    b.Property<DateTime>("time");

                    b.Property<string>("title");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("ActivityId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("DojoActivityCenter.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("fname");

                    b.Property<string>("lname");

                    b.Property<string>("password");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DojoActivityCenter.Models.UserActivity", b =>
                {
                    b.Property<int>("UserActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivityId");

                    b.Property<int>("UserId");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("UserActivityId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivity");
                });

            modelBuilder.Entity("DojoActivityCenter.Models.UserActivity", b =>
                {
                    b.HasOne("DojoActivityCenter.Models.Activity", "Activity")
                        .WithMany("UserActivity")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DojoActivityCenter.Models.User", "User")
                        .WithMany("UserActivity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
